# -*- coding: utf-8 -*-

AREAS = [
{
 "slug":"advogado-divorcio-brasilia",
 "nome":"Divórcio e partilha",
 "assunto":"Divórcio e partilha",
 "title_tag":"Advogado de Divórcio em Brasília | PCB Advogados",
 "description":"Divórcio consensual ou litigioso, dissolução de união estável e partilha de bens em Brasília. Atendimento presencial em Águas Claras e Asa Sul ou online.",
 "kicker":"Divórcio · União estável · Partilha de bens",
 "h1":"Advogado de divórcio em Brasília",
 "h1_em":"para você decidir sabendo o que está em jogo",
 "lead":"Consensual ou litigioso, em cartório ou na Justiça. O PCB organiza o cenário, explica os caminhos possíveis e cuida da partilha de bens com você entendendo cada passo.",
 "situacoes_tit":"Situações que o escritório conduz nessa área",
 "situacoes":[
   ("Divórcio consensual","As duas partes de acordo. Quando não há filhos menores nem gravidez, pode ser resolvido por escritura em cartório, sem processo judicial."),
   ("Divórcio litigioso","Sem acordo sobre partilha, guarda ou pensão. O divórcio é concedido de qualquer forma e os efeitos são decididos no processo."),
   ("Partilha de bens","Imóvel financiado, empresa, FGTS, bens recebidos por herança. O regime de bens define o ponto de partida, e cada item precisa de análise."),
   ("Dissolução de união estável","Sem contrato escrito, vale a comunhão parcial. A prova da relação e da data de início costuma ser o ponto central."),
   ("Divórcio com um dos cônjuges em outra cidade ou país","Possível, com procuração e adaptação do rito."),
   ("Alteração de nome","Retomada do nome de solteiro no mesmo procedimento."),
 ],
 "objecoes":[
   ("“Vai virar uma briga?”","Depende do grau de acordo sobre os efeitos, não do divórcio em si. Muitos casos começam litigiosos e terminam em acordo parcial, o que encurta bastante o caminho."),
   ("“Quanto tempo leva?”","A via extrajudicial pode ser resolvida em uma sessão quando a documentação está completa. Na Justiça, o prazo depende da vara e da complexidade da partilha."),
   ("“Preciso do consentimento da outra pessoa?”","Não. O divórcio não depende da vontade dos dois. A falta de acordo apenas define que a via será judicial."),
 ],
 "faq":[
   ("Dá para me divorciar sem partilhar os bens agora?","Sim. É possível decretar o divórcio e deixar a partilha para depois. É uma decisão estratégica, com vantagens e riscos que precisam ser avaliados no caso concreto."),
   ("Quais bens entram na partilha?","Depende do regime de bens. Na comunhão parcial, regime da maioria dos casamentos, partilham-se os bens adquiridos onerosamente durante o casamento, independentemente de em nome de quem estejam."),
   ("As dívidas também são divididas?","Dívidas contraídas em proveito da família durante o casamento, em regra, entram na conta. Dívidas pessoais e anteriores seguem regra própria."),
   ("Preciso de advogado para o divórcio em cartório?","Sim. A presença de advogado é obrigatória também na via extrajudicial, e é ele quem assina a escritura junto com as partes."),
 ],
 "wa":"Olá, preciso de orientação sobre divórcio e partilha de bens",
},
{
 "slug":"advogado-inventario-brasilia",
 "nome":"Inventário e herança",
 "assunto":"Inventário e herança",
 "title_tag":"Advogado de Inventário em Brasília | PCB Advogados",
 "description":"Inventário judicial e extrajudicial, partilha de herança, testamento e planejamento sucessório em Brasília. Atendimento presencial ou online.",
 "kicker":"Inventário · Herança · Testamento · Sucessão",
 "h1":"Advogado de inventário em Brasília",
 "h1_em":"para resolver pela via mais rápida que o seu caso permite",
 "lead":"Cartório ou Justiça, a diferença está em três condições objetivas. O PCB verifica qual via cabe no seu caso, organiza a documentação e conduz a partilha dos bens.",
 "situacoes_tit":"Situações que o escritório conduz nessa área",
 "situacoes":[
   ("Inventário extrajudicial","Em cartório, quando há acordo entre todos os herdeiros, nenhum é menor ou incapaz e não existe testamento. É a via mais rápida."),
   ("Inventário judicial","Quando falta acordo, há herdeiro menor ou incapaz, testamento, ou disputa sobre bens e herdeiros."),
   ("Arrolamento sumário","Rito judicial simplificado para herdeiros maiores, capazes e de acordo, usado quando algo impede o cartório."),
   ("Partilha de herança","Separar a meação do cônjuge ou companheiro do acervo que efetivamente se transmite. É onde mais aparece erro de cálculo."),
   ("Testamento e planejamento sucessório","Organizar em vida, com segurança jurídica, o que a família vai receber."),
   ("Holding familiar","Estrutura societária para organizar patrimônio e sucessão."),
 ],
 "objecoes":[
   ("“Passou dos 60 dias, e agora?”","O inventário continua possível. O que normalmente acontece é a incidência de multa sobre o ITCMD, cobrada no momento do recolhimento."),
   ("“Cabe no cartório?”","Três condições precisam estar presentes ao mesmo tempo: acordo entre todos os herdeiros, nenhum herdeiro menor ou incapaz e inexistência de testamento."),
   ("“Dá para vender o imóvel antes de terminar?”","Em regra não antes da partilha, porque o bem ainda integra o espólio. Em situações específicas cabe pedir autorização judicial."),
 ],
 "faq":[
   ("Preciso de advogado para inventário em cartório?","Sim. A presença de advogado é obrigatória em qualquer inventário no Brasil, judicial ou extrajudicial."),
   ("Quanto tempo demora um inventário?","A via extrajudicial costuma ser muito mais rápida que a judicial. Nas duas, a etapa mais longa quase sempre é reunir a documentação dos bens e as certidões."),
   ("Herdeiro que mora em outro estado atrapalha?","Não. A participação pode ser feita por procuração, desde que haja acordo."),
   ("E se um herdeiro não concordar?","A via extrajudicial fica inviável e o caso segue para o inventário judicial, onde a partilha é decidida no processo."),
 ],
 "wa":"Olá, preciso de orientação sobre inventário e partilha de herança",
},
{
 "slug":"advogado-guarda-brasilia",
 "nome":"Guarda e convivência",
 "assunto":"Guarda e convivência",
 "title_tag":"Advogado de Guarda de Filhos em Brasília | PCB Advogados",
 "description":"Guarda compartilhada ou unilateral, regulamentação de convivência e alienação parental em Brasília. Atendimento presencial ou online.",
 "kicker":"Guarda · Convivência · Alienação parental",
 "h1":"Advogado de guarda de filhos em Brasília",
 "h1_em":"com firmeza jurídica e sem aumentar o conflito",
 "lead":"Guarda trata de decidir junto. Convivência trata de organizar o tempo. São coisas diferentes, e entender essa separação muda completamente o que esperar do processo.",
 "situacoes_tit":"Situações que o escritório conduz nessa área",
 "situacoes":[
   ("Guarda compartilhada","Regra legal quando os dois genitores têm condições de exercer o poder familiar. Não depende de boa relação entre os pais."),
   ("Guarda unilateral","Exceção, reservada a casos em que um dos genitores não tem condições, não deseja a guarda ou representa risco à criança."),
   ("Regulamentação de convivência","Desenhar o calendário sobre a realidade concreta: distância, escola, idade da criança, rotina de trabalho."),
   ("Revisão do acordo de convivência","O que serve a uma criança de três anos raramente serve a um adolescente de quinze."),
   ("Alienação parental","Dificultar o contato, desqualificar o outro, criar obstáculos à convivência. A constatação depende de prova."),
   ("Mudança de cidade com o filho","Precisa de concordância ou autorização judicial, com análise do melhor interesse da criança."),
 ],
 "objecoes":[
   ("“Guarda compartilhada obriga a alternar de casa?”","Não. A residência pode ser fixa com um dos pais. O compartilhamento é das decisões relevantes sobre a vida do filho."),
   ("“Pai também consegue a guarda?”","A lei não distingue. O que o juiz analisa é a rotina da criança, a capacidade de cada genitor e o melhor interesse do filho."),
   ("“Quanto tempo leva?”","Varia conforme a necessidade de estudo psicossocial e o grau de conflito. Medidas urgentes podem ser pedidas em caráter liminar."),
 ],
 "faq":[
   ("Quem tem guarda compartilhada paga pensão?","Sim, pode pagar. Guarda e pensão são questões independentes, e a pensão equilibra as despesas conforme a capacidade de cada genitor e o tempo de convivência."),
   ("A criança escolhe com quem vai morar?","A vontade da criança ou do adolescente é ouvida e ponderada conforme a idade e a maturidade, mas não decide sozinha."),
   ("Posso impedir visitas se a pensão não é paga?","Não. São obrigações independentes, e condicionar uma à outra pode ser interpretado como alienação parental."),
   ("Como se prova alienação parental?","Principalmente pelo estudo psicossocial determinado pelo juízo, somado a provas de condutas concretas de obstrução do contato."),
 ],
 "wa":"Olá, preciso de orientação sobre guarda e convivência com meu filho",
},
{
 "slug":"advogado-pensao-alimenticia-brasilia",
 "nome":"Pensão alimentícia",
 "assunto":"Pensão alimentícia",
 "title_tag":"Advogado de Pensão Alimentícia em Brasília | PCB Advogados",
 "description":"Fixação, revisão, exoneração e cobrança de pensão alimentícia atrasada em Brasília. Atendimento presencial em Águas Claras e Asa Sul ou online.",
 "kicker":"Fixação · Revisão · Exoneração · Cobrança",
 "h1":"Advogado de pensão alimentícia em Brasília",
 "h1_em":"para fixar, revisar ou cobrar o que é devido",
 "lead":"Não existe percentual fixo. O valor sai do que a criança precisa e do que o pagante pode, e muda quando essa realidade muda. São quatro frentes diferentes, cada uma com o seu procedimento.",
 "situacoes_tit":"Situações que o escritório conduz nessa área",
 "situacoes":[
   ("Fixação de pensão","Definir o valor a partir da necessidade de quem recebe e da possibilidade de quem paga, com análise de renda formal ou informal."),
   ("Cobrança de pensão atrasada","Dois ritos distintos: o das três últimas parcelas, que admite prisão civil, e o das parcelas mais antigas, com penhora e bloqueio."),
   ("Revisão de pensão","Perda de emprego, novo filho, mudança de escola, aumento de renda. Exige ação própria e prova da mudança."),
   ("Exoneração","A maioridade não extingue sozinha o encargo. A cessação depende de pedido e decisão judicial."),
   ("Pensão entre ex-cônjuges","Instituto distinto da pensão do filho, em geral transitória, para reorganização econômica."),
   ("Desconto em folha e bloqueio de valores","Medidas de efetivação quando o pagamento não acontece de forma espontânea."),
 ],
 "objecoes":[
   ("“Pensão é 30% do salário?”","Não existe percentual legal. O mesmo salário pode gerar valores bem diferentes conforme o número de filhos, a idade e as despesas específicas."),
   ("“O pai é autônomo e diz que não ganha nada.”","A análise usa movimentação bancária, imposto de renda, pró-labore, distribuição de lucros e sinais exteriores de riqueza. Quando a renda é informal, é comum a fixação sobre o salário mínimo."),
   ("“Perdi o emprego, posso pagar menos?”","Não por conta própria. Reduzir sem decisão judicial gera dívida e mantém o risco de prisão civil. O caminho é a ação revisional, pagando o possível e documentando."),
 ],
 "faq":[
   ("Quantos meses de atraso permitem pedir a prisão?","O rito da prisão alcança as três prestações vencidas antes do ajuizamento, mais as que vencerem durante o processo. As parcelas mais antigas seguem pelo rito de penhora."),
   ("A prisão quita a dívida?","Não. O cumprimento da prisão não extingue o débito, que continua sendo cobrado pelos demais meios."),
   ("A pensão incide sobre décimo terceiro e férias?","Depende do que foi definido no acordo ou na decisão. É um ponto que precisa ser tratado expressamente, porque não há regra automática."),
   ("Até que idade o filho tem direito?","Não acaba automaticamente aos 18. O encargo pode continuar enquanto o filho estiver estudando e não tiver condições de se manter."),
 ],
 "wa":"Olá, preciso de orientação sobre pensão alimentícia",
},
]
